name = "esprey-tasks-email"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[vars]
ADMIN_EMAIL = "cesprey@gmail.com"
ADMIN_NAME = "Carl"
APP_DOMAIN = "tasks.esprey.net"

[triggers]
crons = ["0 3 * * *"] # daily 03:00 UTC — prune completed tasks older than 1 month

[[d1_databases]]
binding = "DB"
database_name = "esprey-tasks-app"
database_id = "04508e88-feb9-435d-9740-2affcf5206df"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "esprey-tasks-app-attachments"
